In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv("./College_Data.csv")

In [4]:
df.head()

Unnamed: 0 Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0   70        78       18.1           12    7041         60  
1   29        30       12.2           16   10527         56  
2   53        66       12.9           30    8735         54  
3   92        97        7.7           37   19016         59  
4   76        72       11.9            2   10922         15

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 19 columns):
Unnamed: 0     777 non-null object
Private        777 non-null object
Apps           777 non-null int64
Accept         777 non-null int64
Enroll         777 non-null int64
Top10perc      777 non-null int64
Top25perc      777 non-null int64
F.Undergrad    777 non-null int64
P.Undergrad    777 non-null int64
Outstate       777 non-null int64
Room.Board     777 non-null int64
Books          777 non-null int64
Personal       777 non-null int64
PhD            777 non-null int64
Terminal       777 non-null int64
S.F.Ratio      777 non-null float64
perc.alumni    777 non-null int64
Expend         777 non-null int64
Grad.Rate      777 non-null int64
dtypes: float64(1), int64(16), object(2)
memory usage: 115.5+ KB


In [6]:
df.rename(columns = {'Unnamed: 0' : 'Name'}, inplace = True)
df.head()

Name Private  Apps  Accept  Enroll  Top10perc  \
0  Abilene Christian University     Yes  1660    1232     721         23   
1            Adelphi University     Yes  2186    1924     512         16   
2                Adrian College     Yes  1428    1097     336         22   
3           Agnes Scott College     Yes   417     349     137         60   
4     Alaska Pacific University     Yes   193     146      55         16   

   Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  Personal  \
0         52         2885          537      7440        3300    450      2200   
1         29         2683         1227     12280        6450    750      1500   
2         50         1036           99     11250        3750    400      1165   
3         89          510           63     12960        5450    450       875   
4         44          249          869      7560        4120    800      1500   

   PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0   70        78       18.1           12    7041         60  
1   29        30       12.2           16   10527         56  
2   53        66       12.9           30    8735         54  
3   92        97        7.7           37   19016         59  
4   76        72       11.9            2   10922         15

In [7]:
df_scaled = pd.DataFrame()
for x in df.columns[2:]:
    y = (df[x] - df[x].mean())/df[x].std()
    df_scaled = pd.concat([df_scaled, y], axis=1)
df_scaled.head()

Apps    Accept    Enroll  Top10perc  Top25perc  F.Undergrad  \
0 -0.346659 -0.320999 -0.063468  -0.258416  -0.191704    -0.168008   
1 -0.210748 -0.038678 -0.288398  -0.655234  -1.353040    -0.209653   
2 -0.406604 -0.376076 -0.477814  -0.315105  -0.292690    -0.549212   
3 -0.667830 -0.681243 -0.691982   1.839046   1.676532    -0.657656   
4 -0.725709 -0.764063 -0.780232  -0.655234  -0.595647    -0.711466   

   P.Undergrad  Outstate  Room.Board     Books  Personal       PhD  Terminal  \
0    -0.209072 -0.745875   -0.964284 -0.601924  1.269228 -0.162923 -0.115654   
1     0.244150  0.457202    1.907979  1.215097  0.235363 -2.673923 -3.376001   
2    -0.496770  0.201175   -0.553960 -0.904761 -0.259415 -1.204069 -0.930741   
3    -0.520416  0.626229    0.996150 -0.601924 -0.687730  1.184443  1.174900   
4     0.009000 -0.716047   -0.216584  1.517934  0.235363  0.204540 -0.523198   

   S.F.Ratio  perc.alumni    Expend  Grad.Rate  
0   1.013123    -0.867016 -0.501587  -0.318047  
1  -0.477397    -0.544222  0.166003  -0.550907  
2  -0.300556     0.585558 -0.177176  -0.667337  
3  -1.614235     1.150447  1.791697  -0.376262  
4  -0.553186    -1.674001  0.241648  -2.937721

In [8]:
K = 2

In [9]:
clusters = []
for x in range (len(df)):
    clusters.append(np.random.randint(2))
print(clusters)

[1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 

In [10]:
df['Cluster'] = pd.Series(clusters)
df_scaled['Cluster'] = pd.Series(clusters)
df_scaled.head()

Apps    Accept    Enroll  Top10perc  Top25perc  F.Undergrad  \
0 -0.346659 -0.320999 -0.063468  -0.258416  -0.191704    -0.168008   
1 -0.210748 -0.038678 -0.288398  -0.655234  -1.353040    -0.209653   
2 -0.406604 -0.376076 -0.477814  -0.315105  -0.292690    -0.549212   
3 -0.667830 -0.681243 -0.691982   1.839046   1.676532    -0.657656   
4 -0.725709 -0.764063 -0.780232  -0.655234  -0.595647    -0.711466   

   P.Undergrad  Outstate  Room.Board     Books  Personal       PhD  Terminal  \
0    -0.209072 -0.745875   -0.964284 -0.601924  1.269228 -0.162923 -0.115654   
1     0.244150  0.457202    1.907979  1.215097  0.235363 -2.673923 -3.376001   
2    -0.496770  0.201175   -0.553960 -0.904761 -0.259415 -1.204069 -0.930741   
3    -0.520416  0.626229    0.996150 -0.601924 -0.687730  1.184443  1.174900   
4     0.009000 -0.716047   -0.216584  1.517934  0.235363  0.204540 -0.523198   

   S.F.Ratio  perc.alumni    Expend  Grad.Rate  Cluster  
0   1.013123    -0.867016 -0.501587  -0.318047        1  
1  -0.477397    -0.544222  0.166003  -0.550907        0  
2  -0.300556     0.585558 -0.177176  -0.667337        0  
3  -1.614235     1.150447  1.791697  -0.376262        1  
4  -0.553186    -1.674001  0.241648  -2.937721        0

In [11]:
df['Private'] = df['Private'].apply(lambda x: 1 if x == 'Yes' else 0)

In [12]:
df['Private'].value_counts(), df_scaled['Cluster'].value_counts()

(1    565
 0    212
 Name: Private, dtype: int64,
 1    402
 0    375
 Name: Cluster, dtype: int64)

In [13]:
def get_centroids(df):
    centroids = []
    for c in range(K):
        centroid = np.array(df[df['Cluster'] == c].iloc[:, :-1].mean())
        centroids.append(centroid)
    return centroids

In [14]:
centroids = get_centroids(df.iloc[:, 2:])
centroids

[array([ 3079.05066667,  2016.96266667,   766.67466667,    27.82666667,
           55.76      ,  3621.20266667,   841.81333333, 10545.47466667,
         4400.384     ,   560.832     ,  1327.544     ,    72.968     ,
           80.02133333,    13.9576    ,    23.52      ,  9910.49866667,
           64.65066667]),
 array([ 2929.42537313,  2020.52238806,   792.37810945,    27.30845771,
           55.83084577,  3773.32587065,   867.87810945, 10342.90298507,
         4317.54726368,   538.69900498,  1352.86069652,    72.37313433,
           79.40547264,    14.21293532,    22.0199005 ,  9426.65671642,
           66.22139303])]

In [15]:
# new_clusters = []
# for x, val in df_scaled.iterrows():
#     dist = []
#     for c in range(len(centroids)):
#         dist.append(np.linalg.norm(val[:-1] - centroids[c]))
#     min_dist = min(dist)
#     new_clusters.append(dist.index(min_dist))
# df_scaled['Cluster'] =  new_clusters
# print(new_clusters)
# print(df_scaled['Cluster'].value_counts())

In [16]:
new_clusters = []
for x, val in df.iterrows():
    dist = []
    for c in range(len(centroids)):
        dist.append(np.linalg.norm(val[2 :-1] - centroids[c]))
    min_dist = min(dist)
    new_clusters.append(dist.index(min_dist))
df['Cluster'] =  new_clusters
print(new_clusters)
print(df['Cluster'].value_counts())

[1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 

In [17]:
# centroids = get_centroids(df_scaled)
# centroids

In [18]:
centroids = get_centroids(df.iloc[:, 2:])
centroids

[array([3.47239799e+03, 2.11060535e+03, 6.91528428e+02, 3.80936455e+01,
        6.62709030e+01, 2.94434783e+03, 6.05488294e+02, 1.42475284e+04,
        5.14868562e+03, 5.66866221e+02, 1.18114047e+03, 8.08929766e+01,
        8.75986622e+01, 1.16608696e+01, 2.92775920e+01, 1.37165652e+04,
        7.41070234e+01]),
 array([2707.16736402, 1961.38075314,  835.29707113,   20.96861925,
          49.24476987, 4172.52719665, 1011.56066946, 8059.39121339,
        3862.63807531,  538.44351464, 1440.41422594,   67.51046025,
          74.76359833,   15.60899582,   18.65690377, 7122.80334728,
          60.05648536])]

In [19]:
# while clusters != new_clusters:
#     clusters = new_clusters
    
#     new_clusters = []
#     ## Find closest centroid for each datapoint
#     for x, val in df_scaled.iterrows():
#         dist = []
#         for c in range(len(centroids)):
#             dist.append(np.linalg.norm(val[:-1] - centroids[c]))
#         min_dist = min(dist)
#         new_clusters.append(dist.index(min_dist))
    
#     ## Assign new clusters
#     df_scaled['Cluster'] =  new_clusters
    
#     ## Calculate and update new centroids
#     centroids = get_centroids(df_scaled)
    
#     print(new_clusters.count(0), new_clusters.count(1))

In [20]:
while clusters != new_clusters:
    clusters = new_clusters
    
    new_clusters = []
    ## Find closest centroid for each datapoint
    for x, val in df.iterrows():
        dist = []
        for c in range(len(centroids)):
            dist.append(np.linalg.norm(val[2 :-1] - centroids[c]))
        min_dist = min(dist)
        new_clusters.append(dist.index(min_dist))
    
    ## Assign new clusters
    df['Cluster'] =  new_clusters
    
    ## Calculate and update new centroids
    centroids = get_centroids(df.iloc[:, 2:])
    
    print(new_clusters.count(0), new_clusters.count(1))

245 532
213 564
186 591
168 609
161 616
157 620
156 621
156 621
159 618
161 616
163 614
168 609
169 608
161 616
146 631
131 646
121 656
113 664
108 669
108 669


In [44]:
from sklearn.cluster import KMeans

In [45]:
kmeans = KMeans(n_clusters=2)

In [46]:
kmeans.fit(df.iloc[:, 2 :-1])

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [47]:
kmeans.cluster_centers_

array([[1.81323468e+03, 1.28716592e+03, 4.91044843e+02, 2.53094170e+01,
        5.34708520e+01, 2.18854858e+03, 5.95458894e+02, 1.03957085e+04,
        4.31136472e+03, 5.41982063e+02, 1.28033632e+03, 7.04424514e+01,
        7.78251121e+01, 1.40997010e+01, 2.31748879e+01, 8.93204634e+03,
        6.51195815e+01],
       [1.03631389e+04, 6.55089815e+03, 2.56972222e+03, 4.14907407e+01,
        7.02037037e+01, 1.30619352e+04, 2.46486111e+03, 1.07191759e+04,
        4.64347222e+03, 5.95212963e+02, 1.71420370e+03, 8.63981481e+01,
        9.13333333e+01, 1.40277778e+01, 2.00740741e+01, 1.41705000e+04,
        6.75925926e+01]])

In [48]:
centroids

[array([1.03631389e+04, 6.55089815e+03, 2.56972222e+03, 4.14907407e+01,
        7.02037037e+01, 1.30619352e+04, 2.46486111e+03, 1.07191759e+04,
        4.64347222e+03, 5.95212963e+02, 1.71420370e+03, 8.63981481e+01,
        9.13333333e+01, 1.40277778e+01, 2.00740741e+01, 1.41705000e+04,
        6.75925926e+01]),
 array([ 1813.23467862,  1287.16591928,   491.04484305,    25.30941704,
           53.47085202,  2188.54857997,   595.45889387, 10395.70852018,
         4311.36472347,   541.98206278,  1280.33632287,    70.44245142,
           77.82511211,    14.09970105,    23.17488789,  8932.04633782,
           65.11958146])]

In [49]:
sum(kmeans.labels_ == 1)

108

In [50]:
print(new_clusters)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 